### ISSUE TITLE
how to run Badasp.py file 

### ISSUE THREAD

**Issue by pritijadhao510** [slimsuite/SLiMSuite#4]
hello
what are step to successfully run the badasp.py file from SilmSuite i read the its mannual of it i didn't found my solution kindly help me.
![Badasp python](https://user-images.githubusercontent.com/53395866/69347915-51cbdb00-0c9b-11ea-8cbd-f1723a169c04.jpg)

**Comment by cabbagesofdoom** [comment]
Sorry, this issue was posted during a rather busy period and got buried. Are you still looking for a solution? The settings need to be given as commandline arguments, or provided in an `*.ini` file. See here: <http://slimsuite.blogspot.com/2013/08/command-line-options.html>
